languageCode = "en-us"
title = "Massively"
baseURL = "https://stdint.github.io/"
theme = "massively"
#googleanalytics = ""
#disqusShortname = ""

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"
[languages.zh]
  languageName = "中文"
  title = "Massively - Versión 中文"
