#!/usr/bin/env bash

if [[ $# == 1 ]]; then
  TITLE=`date "+%Y-%m-%d-$1"`
  FILE=_posts/$TITLE.markdown
  touch $FILE

  echo "---" > $FILE
  echo "layout: post" >> $FILE
  echo "title: \"$1\"" >> $FILE
  date "+date: %Y-%m-%d %H:%M:%S %z" >> $FILE
  echo "categories:" >> $FILE
  echo "---" >> $FILE
fi

